meta_product_name: "Monettary"
meta_title: "Monettary - Safest Crypto Wallet"
meta_description: "Choose Monettary, the safest way to store your monettary energy. Become self-banked and take custody of your own life"
meta_image: "main_logo.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"
